name: nestjs

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:80'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
