name: Docker Build and Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  nest-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: |
          mv Dockerfile.prod Dockerfile
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'leesavage09-nestjs'
          heroku_email: 'leesavage09@gmail.com'
          usedocker: true
